USE QLBH_2020
GO
SET DATEFORMAT DMY

--11. Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK).
CREATE TRIGGER TRIG_CHK_NGHD_NGDK
ON KHACHHANG FOR UPDATE
AS
BEGIN
	DECLARE @NGDK SMALLDATETIME
	DECLARE @NGHD SMALLDATETIME
	SELECT @NGDK = NGDK FROM INSERTED
	IF (@NGDK > ANY (
						SELECT HOADON.NGHD
						FROM HOADON, INSERTED
						WHERE HOADON.MAKH = INSERTED.MAKH
					))
			BEGIN
				PRINT N'NGÀY ĐĂNG KÝ PHẢI NHỎ HƠN NGÀY MUA HÀNG'
				ROLLBACK TRANSACTION
			END
END

CREATE TRIGGER TRIG_CHK_NGHD
ON HOADON FOR INSERT, UPDATE
AS
BEGIN
		DECLARE @NGDK SMALLDATETIME
		DECLARE @NGHD SMALLDATETIME
		SELECT @NGDK = NGDK, @NGHD = NGHD
		FROM INSERTED, KHACHHANG
		WHERE KHACHHANG.MAKH = INSERTED.MAKH
		IF (@NGDK>@NGHD)
		BEGIN
			PRINT N'NGÀY LẬP HOÁ ĐƠN PHẢI LỚN HƠN NGÀY ĐĂNG KÝ CỦA KHÁCH HÀNG'
			ROLLBACK TRANSACTION
		END
		ELSE
			PRINT N'CẬP NHẬT/THÊM THÀNH CÔNG'
END
						
--12. Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.CREATE TRIGGER TRIG_CHK_NGVL ON HOADON FOR INSERT, UPDATEASBEGIN		DECLARE @NGHD SMALLDATETIME		DECLARE @NGVL SMALLDATETIME		SELECT @NGVL = NGVL FROM NHANVIEN, INSERTED		IF (@NGVL > ANY (							SELECT HOADON.NGHD							FROM HOADON, INSERTED							WHERE HOADON.MANV = INSERTED.MANV							)			)		BEGIN			PRINT N'NGÀY BÁN HÀNG CỦA NHÂN VIÊN PHẢI LỚN HƠN HOẶC BẰNG NGÀY NHÂN VIÊN ĐÓ VÀO LÀM'			ROLLBACK TRANSACTION		ENDENDCREATE TRIGGER TRIG_CHK_NGVL_NVON NHANVIEN FOR UPDATEASBEGIN		DECLARE @NGHD SMALLDATETIME		DECLARE @NGVL SMALLDATETIME		SELECT @NGHD = NGHD FROM HOADON, INSERTED		IF (@NGHD < ANY (							SELECT NHANVIEN.NGVL							FROM NHANVIEN, INSERTED							WHERE NHANVIEN.MANV = INSERTED.MANV							))		BEGIN			PRINT N'NGÀY BÁN HÀNG CỦA NHÂN VIÊN PHẢI LỚN HƠN HOẶC BẰNG NGÀY NHÂN VIÊN ĐÓ VÀO LÀM'			ROLLBACK TRANSACTION		ENDEND--41. Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
SELECT TOP 1 MONTH(NGHD) AS THANG
FROM HOADON
WHERE EXISTS (
		SELECT MONTH(NGHD), SUM(TRIGIA)
		FROM HOADON
		WHERE YEAR(NGHD) = 2006
		GROUP BY MONTH(NGHD)
)
--42. Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
SELECT CTHD.MASP, SANPHAM.TENSP
FROM CTHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
GROUP BY CTHD.MASP, SANPHAM.TENSP
HAVING SUM(CTHD.SL) = (
						SELECT MIN(TSL)
						FROM (
								SELECT SUM(SL) AS TSL
								FROM CTHD
								JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
								WHERE YEAR(HOADON.NGHD) = 2006
								GROUP BY MASP
						) AS MASP_MIN
)
--43. *Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT NUOCSX, MASP, TENSP
FROM SANPHAM SP1
WHERE GIA = (
				SELECT MAX(GIA)
				FROM SANPHAM SP2
				WHERE SP1.NUOCSX = SP2.NUOCSX)
GROUP BY NUOCSX, MASP, TENSP
--44. Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.SELECT NUOCSXFROM SANPHAMGROUP BY NUOCSXHAVING COUNT(DISTINCT GIA) >= 3